site:
  name: XDYNAMIS
  site: 'https://enzoreyes11.github.io'
  base: '/xdynamis2'
  trailingSlash: false

  #googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: XDYNAMIS
    template: '%s — xdynamis'
  description: "Potencia ty PYME"
  robots:
    index: false
    follow: false
  openGraph:
    site_name: xdynamis
    images:
      - url: '~/assets/images/xdynamis-logo-crop.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@paoladibuccio'
    site: '@paoladibuccio'
    cardType: summary_large_image

i18n:
  language: es
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
